//Login
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";
export const LOGIN_USER = "LOGIN_USER";
export const UPDATE_DATA_CURRENT_USERS = "UPDATE_DATA_CURRENT_USERS";

//data room
export const ADD_DATA_ROOM = "ADD_DATA_ROOM";
export const UPDATE_DATA_ROOM = "UPDATE_DATA_ROOM";
export const DELETE_DATA_ROOM = "DELETE_DATA_ROOM";
export const GET_DATA_ROOM = "GET_DATA";
export const GET_TYPE_DATA = "GET_TYPE_DATA";

//data service
export const GET_DATA_SERVICE = "GET_DATA_SERVICE";
export const ADD_DATA_SERVICE = "ADD_DATA_SERVICE";
export const UPDATE_DATA_SERVICE = "UPDATE_DATA_SERVICE";
export const DELETE_DATA_SERVICE = "DELETE_DATA_SERVICE";

//data Users
export const GET_DATA_USERS = "GET_DATA_USERS";
export const ADD_DATA_USERS = "ADD_DATA_USERS";
export const UPDATE_DATA_USERS = "UPDATE_DATA_USERS";
export const DELETE_DATA_USERS = "DELETE_DATA_USERS";

export const GET_DATA_USERS_LOGIN = "GET_DATA_USERS_LOGIN";

//data Role User
export const GET_DATA_ROLE = "GET_DATA_ROLE";

//data hotels
export const GET_DATA_HOTEL = "GET_DATA_HOTEL";
export const ADD_DATA_HOTEL = "ADD_DATA_HOTEL";
export const DELETE_DATA_HOTEL = "DELETE_DATA_HOTEL";
export const UPDATE_DATA_HOTEL = "UPDATE_DATA_HOTEL";

//data bookroom
export const ADD_DATA_BOOKROOM = "ADD_DATA_BOOKROOM";
export const UPDATE_DATA_BOOKROOM = "UPDATE_DATA_BOOKROOM";
export const DELETE_DATA_BOOKROOM = "DELETE_DATA_BOOKROOM";
export const GET_DATA_BOOKROOM = "GET_DATA_BOOKROOM";
 

//bill
export const CREATE_DATA_BILL = "CREATE_DATA_BILL";
export const GET_DATA_BILL = "GET_DATA_BILL";

